In [1]:
import torch
import numpy as np

In [2]:
# initializing a data

# from data
data = [[1,2], [3,4]]
np_array = np.array(data)

x_data = torch.tensor(data)
print(f"x_data:\n{x_data}")

# from numpy array
x_np = torch.from_numpy(np_array)
print(f"\nnp_array:\n{np_array}")
print(f"x_np:\n{x_np}")

# from another tensor
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_ones = torch.ones_like(x_data)
print(f"\nOnes Tensor: \n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"\nRandom Tensor: \n {x_rand}")

# using shape
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"\nRandom Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

x_data:
tensor([[1, 2],
        [3, 4]])

np_array:
[[1 2]
 [3 4]]
x_np:
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.6369, 0.3899],
        [0.5872, 0.2184]])

Random Tensor: 
 tensor([[0.0219, 0.3537, 0.1732],
        [0.6471, 0.9515, 0.7932]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# attributes of a tensor
tensor = torch.rand(3,4)
print(f"\n{tensor.shape = }")
print(f"{tensor.size() = }")
print(f"{tensor.dtype = }")
print(f"{tensor.device = }")


tensor.shape = torch.Size([3, 4])
tensor.size() = torch.Size([3, 4])
tensor.dtype = torch.float32
tensor.device = device(type='cpu')


# Operations on Tensors
torch operation can be found [here](https://pytorch.org/docs/stable/torch.html)

In [4]:
# moving to GPU
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [5]:
# slicing
tensor = torch.ones(3,4)
print(f"tensor:\n{tensor}")
print(f"first row: {tensor[0]}")
print(f"first col: {tensor[:,0]}")
print(f"last col: {tensor[...,-1]}")

tensor[:,1] = 0
print(f"tensor:\n{tensor}")

tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first row: tensor([1., 1., 1., 1.])
first col: tensor([1., 1., 1.])
last col: tensor([1., 1., 1.])
tensor:
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [6]:
# join tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"t1\n{t1}")

t1
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [7]:
# arithmetic ops
## matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(f"y1:\n{y1}")

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

## element wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f"z3:\n{z3}")

y1:
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
z3:
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
# converting single element tensor to a python numerical value
agg = tensor.sum()
agg_item = agg.item() # .item() converts to a python numerical value 
print(f"{agg = }")
print(f"{agg_item = }, {type(agg_item)}")

agg = tensor(9.)
agg_item = 9.0, <class 'float'>


## inplace operations 
(24 dec 2023, pytorch says their derivative can be problematic and is discouraged to use)

In [9]:
print(f"{tensor}")
tensor.add_(5)
print(f"{tensor}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# bridging with numpy 

In [10]:
t = torch.ones(5)
n = t.numpy()
print(f"t: {t}")
print(f"n: {n}")

# A change in tensor reflects in the numpy array and vice versa
t.add_(1)
print(f"\nt: {t}")
print(f"n: {n}")

n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"\nt: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
